#[derive(Debug)]
pub enum Instr {
    GetStack(usize),
    SetStack(usize),
    PushInt(i32),
    PushBool(bool),
    PushStr(String),
    GetGlobal(usize),
    SetGlobal(usize),
    Negate,
    Add,
    Sub,
    Mul,
    Div,
    Eq,
    Print,
    Jump(usize),
    JumpIfNot(usize),
}
