#[derive(Debug)]
pub enum Instr {
    GetStack(usize),
    SetStack(usize),
    PopStack(usize),
    PushInt(i32),
    PushBool(bool),
    PushStr(String),
    PushAddr(usize),
    GetGlobal(usize),
    SetGlobal(usize),
    Negate,
    Add,
    Sub,
    Mul,
    Div,
    Eq,
    Less,
    Print,
    Jump,
    JumpIfNot,
    PushCur,
    Call(String, usize),
    Def(String, usize),
    Return,
}
